name = "GraphModelsForPowerNetworks"
uuid = "c6e2dff2-1b64-4f92-bc5d-89e79d9d6b53"
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
